__include__: [
  '../dataset/mot17_detection.yml',
  '../runtime.yml',
  '../rtdetrv2/include/optimizer.yml',
  '../rtdetrv2/include/rtdetrv2_r50vd.yml',
]

tuning: ./models/rtdetrv2_r18vd_120e_coco.pth
output_dir: ./output/kndetr_mot17

num_classes: 1

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: True
  pretrained: False

HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5
  dropout: 0.1

RTDETRTransformerv2:
  num_layers: 3
  num_denoising: 0
  dropout: 0.1

epoches: 20
use_focal_loss: True

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.
  lr: 0.00005
  betas: [0.9, 0.999]
  weight_decay: 0.001

lr_scheduler:
  type: MultiStepLR
  milestones: [12, 16]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 2
